# NOTE: Plotting script mostly generated by Google Gemini
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

file_pattern = "./data/ising_L*.csv"
csv_files = glob.glob(file_pattern)

if not csv_files:
    print(f"No files found matching {file_pattern}. Run the simulation first")
    exit()

# Set up a 1x2 grid of plots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

analytical_plotted = False

# Sort the files so L=2 plots before L=3, etc.
for file in sorted(csv_files):
    # Extract the L value from the filename (e.g., "ising_L2.csv" -> "2")
    basename = os.path.basename(file)
    L_str = basename.replace("ising_L", "").replace(".csv", "")

    # Read the data using Pandas
    df = pd.read_csv(file)

    # Plot Analytical data exactly ONCE (since it is the same for all files)
    if not analytical_plotted:
        ax1.plot(
            df["beta_vals"],
            df["anal_energy_density"],
            color="black",
            linestyle="--",
            linewidth=2,
            label="Exact Theory (L→∞)",
        )

        ax2.plot(
            df["beta_vals"],
            df["anal_m"],
            color="black",
            linestyle="--",
            linewidth=2,
            label="Exact Spontaneous M (L→∞)",
        )
        analytical_plotted = True

    # Plot Simulated Energy Density
    ax1.plot(
        df["beta_vals"],
        df["energy_density"],
        marker="o",
        markersize=3,
        linestyle="-",
        alpha=0.8,
        label=f"Sim L={L_str}",
    )

    # Plot Simulated Absolute Magnetization <|m|>
    ax2.plot(
        df["beta_vals"],
        df["m_abs"],
        marker="s",
        markersize=3,
        linestyle="-",
        alpha=0.8,
        label=f"Sim <|m|> L={L_str}",
    )

    # Plot Simulated Raw Magnetization <m> (This should be your flat line at 0!)
    ax2.plot(
        df["beta_vals"], df["m"], linestyle=":", alpha=0.5, label=f"Sim <m> L={L_str}"
    )

# Formatting Subplot 1: Energy Density
ax1.set_title("Energy Density vs. Inverse Temperature")
ax1.set_xlabel("Inverse Temperature (beta)")
ax1.set_ylabel("Energy Density (epsilon)")
ax1.grid(True, linestyle="--", alpha=0.6)
ax1.legend()

# Formatting Subplot 2: Magnetization
ax2.set_title("Magnetization vs. Inverse Temperature")
ax2.set_xlabel("Inverse Temperature (beta)")
ax2.set_ylabel("Magnetization per Spin")
ax2.grid(True, linestyle="--", alpha=0.6)
ax2.legend()

output_path = "./data/ising_phase_transition.png"
plt.savefig(output_path, dpi=300, bbox_inches="tight")
print(f"Plot successfully saved to: {output_path}")

# Optional: Still show the interactive plot on screen
plt.show()
